-- Supabase Schema for Phool Shop

-- 2. Cards Table
CREATE TABLE IF NOT EXISTS public.cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price INT NOT NULL,
  category TEXT DEFAULT 'Cards',
  images TEXT[] DEFAULT ARRAY[]::TEXT[],
  description TEXT DEFAULT '',
  in_stock BOOLEAN DEFAULT true,
  is_custom BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can do everything" ON public.cards FOR ALL USING (
  auth.role() = 'authenticated'
);

CREATE POLICY "Public read cards" ON public.cards FOR SELECT USING (true);

-- 3. Fundraisers Table
CREATE TABLE IF NOT EXISTS public.fundraisers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  goal TEXT NOT NULL,
  active BOOLEAN DEFAULT true,
  product_id BIGINT REFERENCES public.Products(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.fundraisers ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can do everything" ON public.fundraisers FOR ALL USING (
  auth.role() = 'authenticated'
);

CREATE POLICY "Public read fundraisers" ON public.fundraisers FOR SELECT USING (true);

-- 4. Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.Products(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT DEFAULT '',
  approved BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Admins can do everything" ON public.reviews FOR ALL USING (
  auth.role() = 'authenticated'
);

CREATE POLICY "Public read approved reviews" ON public.reviews FOR SELECT USING (approved = true);
